### ISSUE TITLE
AngularJS shimming not working with grunt-browserify

### ISSUE THREAD

**Issue by bclinkinbeard** [thlorenz/browserify-shim#10]
I added a shim-angular.js file with the following contents:

```
'use strict';
/*jshint asi: true*/

var testLib = require('./utils/test-lib')
var test = require('tap').test
  , baseUrl = 'https://raw.github.com/angular/angular.js/master/src/Angular.js'

test('angular', function (t) {
  var shimConfig = { angular: {  exports: 'angular' } }
  t.plan(1)
  testLib(t, { 
      name: 'angular.js'
    , test: function (t, resolved) { t.equals(typeof resolved().init, 'function', 'shims angular') }
    , shimConfig: shimConfig
  })
});
```

and get this output when running `npm test`

```
    Command: "node" "shim-angular.js"
    TAP version 13
    not ok 1 test/shim-angular.js
      ---
        exit:    8
        stderr:  |
          /projects-personal/browserify-shim/test/shim-angular.js:13
              , test: function (t, resolved) { t.equals(typeof resolved().init, 'functio
                                                               ^
          TypeError: undefined is not a function
              at testLib.test (/projects-personal/browserify-shim/test/shim-angular.js:13:54)
              at /projects-personal/browserify-shim/test/utils/test-lib.js:63:9
              at Stream.<anonymous> (/projects-personal/browserify-shim/node_modules/browserify/index.js:141:35)
              at Stream.EventEmitter.emit (events.js:117:20)
              at Stream.handleEnd (/projects-personal/browserify-shim/node_modules/browserify/node_modules/duplexer/index.js:71:21)
              at Stream.EventEmitter.emit (events.js:117:20)
              at drain (/projects-personal/browserify-shim/node_modules/through/index.js:33:23)
              at Stream.stream.queue.stream.push (/projects-personal/browserify-shim/node_modules/through/index.js:41:5)
              at Stream.end (/projects-personal/browserify-shim/node_modules/browserify/index.js:263:14)
              at _end (/projects-personal/browserify-shim/node_modules/through/index.js:61:9)
        command: "node" "shim-angular.js"
      ...

    1..1
    # tests 1
    # fail  1
```

PS - The impress.js test appears to be failing because it times out. Replacing the URL with https://raw.github.com/bartaz/impress.js/master/js/impress.js however, results in this output:

```
not ok test/shim-impress.js ............................. 1/2
    Command: "node" "shim-impress.js"
    TAP version 13
    not ok 1 Error: Parsing file /projects-personal/browserify-shim/test/fixtures/shims/impress.js: Line 2: Unexpected token <
      ---
        file:   /projects-personal/browserify-shim/test/utils/test-lib.js
        line:   55
        column: 22
        stack:  
          - getCaller (/projects-personal/browserify-shim/node_modules/tap/lib/tap-assert.js:418:17)
          - assert (/projects-personal/browserify-shim/node_modules/tap/lib/tap-assert.js:21:16)
          - Function.fail (/projects-personal/browserify-shim/node_modules/tap/lib/tap-assert.js:95:10)
          - Test._testAssert [as fail] (/projects-personal/browserify-shim/node_modules/tap/lib/tap-test.js:86:16)
          - Stream.<anonymous> (/projects-personal/browserify-shim/test/utils/test-lib.js:55:22)
          - Stream.EventEmitter.emit (events.js:117:20)
          - Stream.EventEmitter.emit (events.js:117:20)
          - Stream.EventEmitter.emit (events.js:117:20)
          - parseDeps (/projects-personal/browserify-shim/node_modules/browserify/node_modules/module-deps/index.js:105:27)
          - done (/projects-personal/browserify-shim/node_modules/browserify/node_modules/module-deps/index.js:95:13)
      ...
    ok 2 test/shim-impress.js

    1..2
    # tests 2
    # pass  1
    # fail  1
```
